### ISSUE TITLE
Override the autocomplete menu

### ISSUE THREAD

**Issue by srbhp** [sunjon/stylish.nvim#1]
Hi,
I am using cmp for the autocomplete. How do 
I get the autocomplete menu look like the MENU you have. 
 Sorry if it is a stupid question. 

/Thanks

**Comment by sunjon** [comment]
It's not really made for that. At the moment it's only designed to display (nested) menus generated by neovims builtin menu system.

I'll make a `vim.ui.select` version for flat lists too, but that too is not the interface that cmp uses for completion. 
Also, this particular menu style uses two lines per result item. I wanted something clear and large, that made for better selection with mouse input (which I hope to add). Doubling the size of the completion menu might not be desirable.

Going to close this for now, but I'll keep the idea in mind
