### ISSUE TITLE
module 'stylish.components.nyan' not found

### ISSUE THREAD

**Issue by RoryNesbitt** [sunjon/stylish.nvim#2]
I have just added this to my packer and whenever I try to use anything I get the error:

```
E5113: Error while calling lua chunk: ...site/pack/packer/start/stylish.nvim/lua/stylish/init.lua:7: module 'stylish.components.nyan' not found:
        no field package.preload['stylish.components.nyan']
        no file './stylish/components/nyan.lua'
        no file '/usr/share/luajit-2.0.5/stylish/components/nyan.lua'
        no file '/usr/local/share/lua/5.1/stylish/components/nyan.lua'
        no file '/usr/local/share/lua/5.1/stylish/components/nyan/init.lua'
        no file '/usr/share/lua/5.1/stylish/components/nyan.lua'
        no file '/usr/share/lua/5.1/stylish/components/nyan/init.lua'
        no file './stylish/components/nyan.so'
        no file '/usr/local/lib/lua/5.1/stylish/components/nyan.so'
        no file '/usr/lib/lua/5.1/stylish/components/nyan.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './stylish.so'
        no file '/usr/local/lib/lua/5.1/stylish.so'
        no file '/usr/lib/lua/5.1/stylish.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...site/pack/packer/start/stylish.nvim/lua/stylish/init.lua:7: in main chunk
        [C]: in function 'require'
        /home/rory/.config/nvim/init.lua:19: in main chunk
```

## Reproduce

This is consistent with the instructions in the readme. I added `use 'sunjon/stylish.nvim'` to my packer config then..
`vim.ui.notify = require('stylish').ui_notification()` - Error on opening Neovim
`vim.ui.menu = require('stylish').ui_menu()` - Error on opening Neovim
```
vim.api.nvim_set_keymap(
  'n',
  '<F12>',
  '<Cmd>lua require"stylish".ui_clock()<CR>',
  { noremap = true, silent = true }
)
```
\- Error on pressing F12

**Comment by RoryNesbitt** [comment]
On looking at the repo it looks as if nyan doesn't exist here but is still being required in the init.lua

**Comment by sunjon** [comment]
Yep, I've removed the require now. Let me know if it works.

**Comment by RoryNesbitt** [comment]
That error is gone now but I'm getting different ones. The clock has an issue with calling create_gradiant argument #1 not being a colour. and the norifications have an issue calling ui_notification

I'm updating everything and removing, readding stylish to see what persists

**Comment by sunjon** [comment]
show me the error message.
I was aware that the highlights for the clock background aren't there in the committed version, but I'd had someone test and it simply didn't render the background - the clock rendered okay without errors.
It may be that a change broke something since then.

**Comment by RoryNesbitt** [comment]
Yup both errors persist through a fresh install

`packer.nvim: Error running config for stylish.nvim: [string "..."]:0: attempt to call field 'ui_notification' (a nil value)`

```
E5108: Error executing lua .../packer/start/stylish.nvim/lua/stylish/common/colors.lua:127: bad argument #1 to 'format' (number expected, got nil)
stack traceback:
        [C]: in function 'format'
        .../packer/start/stylish.nvim/lua/stylish/common/colors.lua:127: in function 'create_gradient_map'
        ...cker/start/stylish.nvim/lua/stylish/components/clock.lua:303: in function 'new'
        ...site/pack/packer/start/stylish.nvim/lua/stylish/init.lua:80: in function 'ui_clock'
        [string ":lua"]:1: in main chunk
```

**Comment by RoryNesbitt** [comment]
for the notifications one, your components directory here only has menu and clock. Should that not be where ui_notifications etc are too?

**Comment by sunjon** [comment]
Notifications isn't in there at the moment, You shouldn't try set that up for now (it is commented out in the readme instructions).

The other issue should be fixed. It assumed that there was a highlight group called 'Normal' available. I set it to a default value if it doesn't find it for now. I think ideally it should be setup on a ColorScheme autocommand.

**Comment by RoryNesbitt** [comment]
Ah, in that case I suggest adding your (soon tm) to the notification example

as for clock, new error message, followed by an empty box in the corner:
```
E5108: Error executing lua .../packer/start/stylish.nvim/lua/stylish/common/canvas.lua:3: Vim(autocmd):E216: No such group or event: ModeChanged <buffer> lua require"stylish".event_listener(1005, "FocusLost")
stack traceback:
        [C]: in function 'cmd'
        .../packer/start/stylish.nvim/lua/stylish/common/canvas.lua:3: in function 'set_autocmds'
        .../packer/start/stylish.nvim/lua/stylish/common/canvas.lua:80: in function 'new'
        ...cker/start/stylish.nvim/lua/stylish/components/clock.lua:349: in function 'new'
        ...site/pack/packer/start/stylish.nvim/lua/stylish/init.lua:80: in function 'ui_clock'
        [string ":lua"]:1: in main chunk
```

**Comment by sunjon** [comment]
That's odd.
I've created the autocommands in a bit more of a formal/correct way now. 
That autocommand should only apply to focusable windows too (which the clock isn't), so it should skip that function for clock now too.

**Comment by RoryNesbitt** [comment]
Yeah that's fixed the clock, look forward to getting notifications too!
